<a href="https://colab.research.google.com/github/huypham090300/Pythonnangcao/blob/main/Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chương 8

Bài 1

In [ ]:
kingdoms =['Bacteria','Protozoa','Chromista','Plantae','Fungi','Animalia']
print(kingdoms [0])

Bacteria


In [ ]:
print(kingdoms[5])

Animalia


In [ ]:
print(kingdoms[:3])

['Bacteria', 'Protozoa', 'Chromista']


In [ ]:
print(kingdoms[2:5])

['Chromista', 'Plantae', 'Fungi']


In [ ]:
print(kingdoms[4:])

['Fungi', 'Animalia']


In [ ]:
kingdoms =[]
print(kingdoms)

[]


Bài 2

In [ ]:
kingdoms =['Bacteria','Protozoa','Chromista','Plantae','Fungi','Animalia']
print(kingdoms[-6])

Bacteria


In [ ]:
print(kingdoms[-1])

Animalia


In [ ]:
print(kingdoms[-6:-3])

['Bacteria', 'Protozoa', 'Chromista']


In [ ]:
print(kingdoms[-4:-1])

['Chromista', 'Plantae', 'Fungi']


In [ ]:
print(kingdoms[-2:])

['Fungi', 'Animalia']


In [ ]:
print(kingdoms[-1:-2])

[]


Bài 3

In [ ]:
appointment = ['9:00','10:30','14:00','15:00','15:30']
appointment.append('16:30')
print(appointment)

['9:00', '10:30', '14:00', '15:00', '15:30', '16:30']


In [ ]:
appointment = ['9:00','10:30','14:00','15:00','15:30']
new = ['16:30']
appointment1 = appointment + new
print (appointment1)

['9:00', '10:30', '14:00', '15:00', '15:30', '16:30']


In [ ]:
'#### Theo em cả 2 cách toán tử và append đều giống nhau, đều thêm biến 16:30 vào cuối danh sách và in ra 1 danh sách mới. Nhưng cách toán tử phải cộng theo thứ tự, nếu biến mới cộng danh sách thì khi in ra biến mới sẽ nằm ở đầu danh sách và ngược lại'

'#### Theo em cả 2 cách toán tử và append đều giống nhau, đều thêm biến 16:30 vào cuối danh sách và in ra 1 danh sách mới. Nhưng cách toán tử phải cộng theo thứ tự, nếu biến mới cộng danh sách thì khi in ra biến mới sẽ nằm ở đầu danh sách và ngược lại'

Bài 4

In [ ]:
IDs = [4353,2314,2956,3382,9362,3900]
IDs.remove(3382)
print(IDs)

[4353, 2314, 2956, 9362, 3900]


In [ ]:
IDs.index(9362)

3

In [ ]:
IDs = [4353, 2314, 2956, 9362, 3900]
IDs.insert(4,4499)
print(IDs)

[4353, 2314, 2956, 9362, 4499, 3900]


In [ ]:
IDs = [4353, 2314, 2956, 9362, 4499, 3900]
IDs.extend([5566,1830])
print(IDs)

[4353, 2314, 2956, 9362, 4499, 3900, 5566, 1830]


In [ ]:
IDs = [4353, 2314, 2956, 9362, 4499, 3900, 5566, 1830]
IDs.reverse()
print(IDs)

[1830, 5566, 3900, 4499, 9362, 2956, 2314, 4353]


In [ ]:
IDs = [4353, 2314, 2956, 9362, 4499, 3900, 5566, 1830]
IDs.sort()
print(IDs)

[1830, 2314, 2956, 3900, 4353, 4499, 5566, 9362]


Bài 5

In [ ]:
Kim_loai_kiem_tho = ['berili(4)','magie(12)','canxi(20)','stronti(38)','barium(56)','radium(88)']
print(Kim_loai_kiem_tho)

['berili(4)', 'magie(12)', 'canxi(20)', 'stronti(38)', 'barium(56)', 'radium(88)']


In [ ]:
Kim_loai_kiem_tho[5]

'radium(88)'

In [ ]:
Kim_loai_kiem_tho[-1]

'radium(88)'

In [ ]:
len(Kim_loai_kiem_tho)

6

In [ ]:
import re
Kim_loai_kiem_tho = ['berili(4)','magie(12)','canxi(20)','stronti(38)','barium(56)','radium(88)']
max = 0
pos =0
count=0
for i in Kim_loai_kiem_tho:
  m = re.search(r'\d+',i)
  nt = int(m.group())
  if nt > max:
    max = nt
    pos = count
  count +=1
print(Kim_loai_kiem_tho[pos])

radium(88)


Bài 6

In [ ]:
temps = [25.2,16.8,31.4,23.9,28,22.5,19.6]
print(temps)

[25.2, 16.8, 31.4, 23.9, 28, 22.5, 19.6]


In [ ]:
temps.sort()
print(temps)

[16.8, 19.6, 22.5, 23.9, 25.2, 28, 31.4]


In [ ]:
cool_temps = temps[0:2]
warm_temps = temps[2:]
print(cool_temps)
print(warm_temps)

[16.8, 19.6]
[22.5, 23.9, 25.2, 28, 31.4]


In [ ]:
temps_in_c = warm_temps + cool_temps
print(temps_in_c)

[22.5, 23.9, 25.2, 28, 31.4, 16.8, 19.6]


Bài 7

In [ ]:
def same_first_last(L)-> bool:
  if(len(L) > 2):
    return L[0] == L[-1]
same_first_last([3, 4, 2, 8, 3])

True

In [ ]:
same_first_last(['apple', 'banana', 'pear'])

False

In [ ]:
same_first_last([4.0, 4.5])

False

Bài 8

In [ ]:
def is_longer(L1,L2) -> bool:
  return len(L1) > len(L2)
is_longer([1,2,3],[4,5])

True

In [ ]:
is_longer(['abcdef'], ['ab', 'cd', 'ef'])

False

In [ ]:
is_longer(['a', 'b', 'c'], [1, 2, 3])

False

Bài 9

In [ ]:
values = [0,1,2]
values[1] = values
values

[0, [...], 2]

Bài 10

In [ ]:
units = [['km','miles','league'],['kg','pound','stones']]
units[0]

['km', 'miles', 'league']

In [ ]:
units[1]

['kg', 'pound', 'stones']

In [ ]:
units[0][0]

'km'

In [ ]:
units[1][0]

'kg'

In [ ]:
units[0][1:]

['miles', 'league']

In [ ]:
units[1][0:2]

['kg', 'pound']

Bài 11

In [ ]:
units = [['km','miles','league'],['kg','pound','stones']]
units[-2]

['km', 'miles', 'league']

In [ ]:
units[-1]

['kg', 'pound', 'stones']

In [ ]:
units[-2][-3]

'km'

In [ ]:
units[-1][-3]

'kg'

In [ ]:
units[-2][-2:]

['miles', 'league']

In [ ]:
units[-1][-3:-1]

['kg', 'pound']

Chương 9

Bài 1

In [ ]:
celegans_phenotypes = ['Emb','Him', 'Unc', 'Lon', 'Dpy', 'Sma']
for i in celegans_phenotypes:
  print(i)

Emb
Him
Unc
Lon
Dpy
Sma


Bài 2

In [ ]:
half_live = [87.74, 24110.0, 6537.0, 14.4, 376000.0]
for half_live in half_live:
  print(half_live, end="  ")

87.74  24110.0  6537.0  14.4  376000.0  

Bài 3

In [ ]:
whales = [5, 4, 7, 3, 2, 3, 2, 6, 4, 2, 1, 7, 1, 3]
more_whales = []
for i in whales:
  more_whales.append(i+1)
print(more_whales)

[6, 5, 8, 4, 3, 4, 3, 7, 5, 3, 2, 8, 2, 4]


Bài 4

In [ ]:
alkaline_earth_metals = [[4,12,20,38,56,88],[9.012,24.305,40.078,87.62,137.327,226]]

In [ ]:
for alkaline_earth_metals in alkaline_earth_metals:
  print(alkaline_earth_metals)

[4, 12, 20, 38, 56, 88]
[9.012, 24.305, 40.078, 87.62, 137.327, 226]


In [ ]:
alkaline_earth_metals = [[4,12,20,38,56,88],[9.012,24.305,40.078,87.62,137.327,226]]
[x for number_and_weight in alkaline_earth_metals for x in number_and_weight]

[4, 12, 20, 38, 56, 88, 9.012, 24.305, 40.078, 87.62, 137.327, 226]

Bài 5

In [ ]:
def mystery_function(values):
  result = []
  for sublist in values:
    result.append([sublist[0]])
    for i in sublist[1:]:
      result[-1].insert(0, i)
  return result
mystery_function([[1,2,3],[4,5,6]])

[[3, 2, 1], [6, 5, 4]]

Bài 6

In [ ]:
text = " "
while text.lower() != "quit":
  text = input("Please enter (or 'quit' to exit): ")
  if text == "quit":
    print("Exiting program")
  elif text == "CO2":
    print("Cacbonic")
  elif text == "C6H12O6":
    print("Glucozo")
  else:
    print("Unknown")


Please enter (or 'quit' to exit): C6H12O6
Glucozo
Please enter (or 'quit' to exit): AAA
Unknown
Please enter (or 'quit' to exit): quit
Exiting program


Bài 7

In [ ]:
sum = 0
country_populations =[1295,23,7,3,47,21]
for i in country_populations:
  sum = sum + i
print(sum)

1396


Bài 8

In [ ]:
import numpy as np
rat_1 = np.random.randint(10,size=10)
rat_2 = np.random.randint(10,size=10)
print(rat_1)
print(rat_2)
if (rat_1[0] > rat_2[0]):
  print("Rat 1 weighed more than Rat 2 on day 1")
else:
  print("Rat 2 weighed more than Rat 1 on day 1")

[1 8 0 2 5 4 4 9 1 8]
[2 2 9 4 1 8 0 8 8 6]
Rat 2 weighed more than Rat 1 on day 1


In [ ]:
print(rat_1)
print(rat_2)
if rat_1[0] > rat_2[0] and rat_1[-1] > rat_2[-1]:
  print("Rat 1 remained heavier than Rat 2.")
else:
  print("Rat 2 became heavier than Rat 1.")

[1 8 0 2 5 4 4 9 1 8]
[2 2 9 4 1 8 0 8 8 6]
Rat 2 became heavier than Rat 1.


In [ ]:
if rat_1[0] > rat_2[0]:
  if rat_1[-1] > rat_2[-1]:
    print("Rat 1 remained heavier than Rat 2.")
  else:
    print("Rat 2 became heavier than Rat 1.")
else:
  print("Rat 2 became heavier than Rat 1.")

Rat 2 became heavier than Rat 1.


Bài 9

In [ ]:
for i in range(33,50):
  print(i)

33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


Bài 10

In [ ]:
for i in range(1,11):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

Bài 11

In [ ]:
sum = 0
count = 0
for i in range(2,23):
  sum = sum + i
  count = count + 1
  average = sum / count
print(average)

12.0


Bài 12

In [ ]:
def remove_neg(num_list):
  for i in num_list:
    if num_list[i] < 0:
      del num_list[i]
  print(num_list)
remove_neg([1, 2, 3, -3, 6, -1, -3, 1])

[1, 2, 3, 6, -3, 1]


Bài 13

In [ ]:
for i in range(1,8):
  s = " "
  for j in range(1,i+1):
    s = s + " T"
  print(s)

  T
  T T
  T T T
  T T T T
  T T T T T
  T T T T T T
  T T T T T T T


Bài 14

In [ ]:
n = 8
k = 2*n - 2
for i in range(1,n):
  for j in range(1,k):
    print(end = " ")
  k = k -2
  for j in range(1,i+1):
    print("T", end = " ")
  print("\r")

             T 
           T T 
         T T T 
       T T T T 
     T T T T T 
   T T T T T T 
 T T T T T T T 


Bài 15

In [ ]:
i = 1
while i < 8:
  print("T"*i )
  i += 1

T
TT
TTT
TTTT
TTTTT
TTTTTT
TTTTTTT


In [ ]:
i = 1
while i< 8:
  print(" "*(8-i),"T"*i)
  i += 1

        T
       TT
      TTT
     TTTT
    TTTTT
   TTTTTT
  TTTTTTT



Bài 16

In [26]:
Rat_1_weight = float(10)
Rat_1_rate = 0.25
result = float()
result = (10*0.25+10)*0.4

NameError: ignored